// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJ5YqYNwlzJEQ3LXY3_gchBE1iJ39HiUw',
    appId: '1:182115928051:web:157b6cb9757ca32bf13486',
    messagingSenderId: '182115928051',
    projectId: 'iris-b4d9f',
    authDomain: 'iris-b4d9f.firebaseapp.com',
    databaseURL: 'https://iris-b4d9f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'iris-b4d9f.appspot.com',
    measurementId: 'G-TQ2WMEB9X8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgSpo4jk0F5a0dJ5IBYzObL9sLY71E0d8',
    appId: '1:182115928051:android:b5b9c7149a47bd8af13486',
    messagingSenderId: '182115928051',
    projectId: 'iris-b4d9f',
    databaseURL: 'https://iris-b4d9f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'iris-b4d9f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNL58FnqYtTvyEi5bJHl0pK9pn8Nf2-cA',
    appId: '1:182115928051:ios:e1f7b32c214ee208f13486',
    messagingSenderId: '182115928051',
    projectId: 'iris-b4d9f',
    databaseURL: 'https://iris-b4d9f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'iris-b4d9f.appspot.com',
    iosBundleId: 'com.example.eyetalk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNL58FnqYtTvyEi5bJHl0pK9pn8Nf2-cA',
    appId: '1:182115928051:ios:3e94cc3e2e2ae9b4f13486',
    messagingSenderId: '182115928051',
    projectId: 'iris-b4d9f',
    databaseURL: 'https://iris-b4d9f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'iris-b4d9f.appspot.com',
    iosBundleId: 'com.example.eyetalk.RunnerTests',
  );
}
